### ISSUE TITLE
Android: Could not find com.google.android.gms:play-services-analytics:9.2.0.

### ISSUE THREAD

**Issue by DomGaud** [sitefinitysteve/nativescript-google-analytics#12]
When building for Android using v0.2.9 the following error occurs:

> Could not find com.google.android.gms:play-services-analytics:9.2.0.
>      Searched in the following locations:
>          https://jcenter.bintray.com/com/google/android/gms/play-services-analytics/9.2.0/play-services-analytics-9.2.0.pom
>          https://jcenter.bintray.com/com/google/android/gms/play-services-analytics/9.2.0/play-services-analytics-9.2.0.jar
>          file:/Users/dgaud/Sites/renet/platforms/android/libs/aar/play-services-analytics-9.2.0.jar
>          file:/Users/dgaud/Sites/renet/platforms/android/libs/aar/play-services-analytics.jar
>          https://jitpack.io/com/google/android/gms/play-services-analytics/9.2.0/play-services-analytics-9.2.0.pom
>          https://jitpack.io/com/google/android/gms/play-services-analytics/9.2.0/play-services-analytics-9.2.0.jar
>          file:/usr/local/opt/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-analytics/9.2.0/play-services-analytics-9.2.0.pom
>          file:/usr/local/opt/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-analytics/9.2.0/play-services-analytics-9.2.0.jar
>          file:/usr/local/opt/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-analytics/9.2.0/play-services-analytics-9.2.0.pom
>          file:/usr/local/opt/android-sdk/extras/google/m2repository/com/google/android/gms/play-services-analytics/9.2.0/play-services-analytics-9.2.0.jar.

To resolve this I changed the following line in the [include.gradle](https://github.com/sitefinitysteve/nativescript-googleanalytics/blob/master/plugin/platforms/android/include.gradle) file:
`compile 'com.google.android.gms:play-services-analytics:9.2.0'` to `compile 'com.google.android.gms:play-services-analytics:+`

_Note: iOS runs with no errors._

**Comment by leocaseiro** [comment]
O confirm the same issue with `nativescript@2.2.0` and `nativescript-angular@0.3.0`

**Comment by leocaseiro** [comment]
I'm still having issues because of the hardcoded version of `com.google.android.gms:play-services-analytics`.

Today, my issue was something missing with `com.google.android.gms.internal.zzadz`.

I'll send a PR with that.

**Comment by sitefinitysteve** [comment]
Added with https://github.com/sitefinitysteve/nativescript-google-analytics/commit/e6ec735f1cc7c8b8689f850c73bf1b46c89d72f6

Thx!
