### ISSUE TITLE
Add Support For UserID Tracking

### ISSUE THREAD

**Issue by spstratis** [sitefinitysteve/nativescript-google-analytics#15]
Would be great to add support for UserID Based tracking as noted [Here](https://support.google.com/analytics/answer/3123662?hl=en&utm_id=ad)

It looks like you have even aready started to implement it based off of some of the code that is commented out in each platforms index files.

**Comment by sitefinitysteve** [comment]
Supported now as of 0.3.2, sorry for the delay
