### ISSUE TITLE
Can't find variable: GAIDictionaryBuilder

### ISSUE THREAD

**Issue by dklinzing** [sitefinitysteve/nativescript-google-analytics#35]
We're getting a weird error in iOS all of a sudden when trying to invoke logView("Home") method.  Has anyone run into this before?  Our code was working previously, but for some reason now new builds aren't working.

JavaScript stack trace:
1   logView@file:///app/tns_modules/nativescript-google-analytics/index.js:52:37
2   pageLoaded@file:///app/components/homeView/homeView.js:25:28
3   notify@file:///app/tns_modules/tns-core-modules/data/observable/observable.js:149:31
4   _emit@file:///app/tns_modules/tns-core-modules/data/observable/observable.js:168:24
5   onLoaded@file:///app/tns_modules/tns-core-modules/ui/core/view-common.js:743:19
6   onLoaded@file:///app/tns_modules/tns-core-modules/ui/page/page-common.js:53:39
7   onLoaded@file:///app/tns_modules/tns-core-modules/ui/page/page.js:260:43
8   viewWillAppear@file:///app/tns_modules/tns-core-modules/ui/page/page.js:150:26
9   UIApplicationMain@[native code]
10  start@file:///app/tns_modules/tns-core-modules/application/application.js:251:30
11  anonymous@file:///app/app.js:67:18
12  evaluate@[native code]
13  moduleEvaluation@[native code]
14  @[native code]
15  promiseReactionJob@[native code]
JavaScript error:
file:///app/tns_modules/nativescript-google-analytics/index.js:52:37: JS ERROR ReferenceError: Can't find variable: GAIDictionaryBuilder

**Comment by dklinzing** [comment]
Anyone have any ideas on this?  Would we be better off using the google analytics for firebase plugin?

**Comment by sitefinitysteve** [comment]
Firebase analytics is pretty bare-bones compared to GA, does this happen to
you in the demo or your app?

**Comment by dklinzing** [comment]
In our app.  It's weird, because the production app is still working, and was working a few weeks ago.  It's just all of a sudden when we try to build the app, we're running into this issue.  

 I'll try the demo app here real quick.

**Comment by dklinzing** [comment]
Yup, it's working on the demo app.  

Weird.  I guess it must be something specific to the app.  I wonder if we need to upgrade everything to v3 or something.  We're on nativescript 2.4.2 right now, using nativescript google analytics 0.3.5.

I'll close this issue.  Thanks for your help.
