### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by Emmandez** [sitefinitysteve/nativescript-google-analytics#44]
Everytime I try to build the application with this plugin, I get this error
```
Unable to apply changes on device: ZY222W2F3Q. Error is: Failed to build plugin nativescript-google-analytics :
Error: Command failed: gradlew.bat -p <MyPath>\platforms\tempPlugin\nativescript_google_analytics assembleRelease -PcompileSdk=android-27 -PbuildToolsVersion=27.0.3 -PsupportVersion=26.0.0-alpha1

```

And then this:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':releaseCompileClasspath'.
> Could not find support-v4.aar (com.android.support:support-v4:26.1.0).
  Searched in the following locations:
      https://jcenter.bintray.com/com/android/support/support-v4/26.1.0/support-v4-26.1.0.aar
```

I have these SDK.
![sdk](https://user-images.githubusercontent.com/17038938/41429816-d0ac2ee0-6fd3-11e8-8484-8f82756638ae.jpg)

And the support library up to date
![supportrepo](https://user-images.githubusercontent.com/17038938/41429817-d0d75f2a-6fd3-11e8-8652-b4fcaf0e9f85.jpg)

tns-android: 4.0.1

I have to mention it does run on IOS

**Comment by sitefinitysteve** [comment]
Closed per #43 Duplicate

Thanks for the info though!
